=== manzamb/SemanticWebinAction/02 - XML - RDF/Solución XML/AppEjemploXML/Ejemplos 2/02-dtd/DTDContactos_2024_1.dtd
<!ELEMENT listaContactos (contacto)+>
<!-- Elemento Raiz del árbol: 
       - Son obligatorios: nombre, apellidos
       - Es opcional (?): fecha_nacimiento
       - Se compone de 1 o más subelementos: se usa +
       - Se compone de 0 o más subelementos: correos-->
<!ELEMENT contacto (nombre, apellidos, fecha_nacimiento?, correos*) >
<!-- Estableciendo los tipos de datos de los elementos hoja de PERSONACONTACTO-->
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT fecha_nacimiento (#PCDATA)>
<!-- Elementos del segundo nivel del arbol-->
<!ELEMENT correos (idcorreo, correo)>
<!ELEMENT idcorreo (#PCDATA)>
<!ELEMENT correo (#PCDATA)>

=== manzamb/SemanticWebinAction/02 - XML - RDF/Solución XML/AppEjemploXML/Ejemplos 2/03-xml/01-Contacto-2024-1-Actualizado.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="../05-xslt/XSLContactos_2024.xslt"?>
<!--<!DOCTYPE listaContactos SYSTEM "../02-dtd/DTDContactos_2024_1.dtd">-->

<listaContactos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                xsi:noNamespaceSchemaLocation="../04-xsd/01-Contacto-2024-1-XSD.xsd">
  <contacto>
    <nombre>Carlos</nombre>
    <apellidos> Diaz Santacruz </apellidos>
    <fecha_nacimiento>1977-10-29</fecha_nacimiento>
    <correos> 
      <correo idcorreo="1">andres.diaz@unicauca.edu.co</correo>
      <correo idcorreo="2">andres.diaz@gmail.com</correo>
    </correos>
  </contacto>
  
  <contacto>
    <nombre>Isabel</nombre>
    <apellidos> Mejia</apellidos>
    <fecha_nacimiento>1977-10-29</fecha_nacimiento>
    <correos>
      <correo idcorreo="1">imejia@unicauca.edu.co</correo>
      <correo idcorreo="2">imejia@hotmail.com</correo>
    </correos>
  </contacto>

  <contacto>
    <nombre>Carlos Alberto</nombre>
    <apellidos>Cobos Lozada</apellidos>
    <fecha_nacimiento>1971-02-11</fecha_nacimiento>
    <correos>
      <correo idcorreo="1">ccobos@unicauca.edu.co</correo>
      <correo idcorreo="2">coboscarlos@gmail.com</correo>
    </correos>
  </contacto>
  
</listaContactos>

=== manzamb/SemanticWebinAction/02 - XML - RDF/Solución XML/AppEjemploXML/Ejemplos 2/03-xml/01-Contacto-2024-1 - DTD.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--<?xml-stylesheet type="text/xsl" href="../05-xslt/XSLContactos.xslt"?>-->
<!DOCTYPE listaContactos SYSTEM "../02-dtd/DTDContactos_2024_1.dtd">

<listaContactos>
  <contacto>
    <nombre>Carlos</nombre>
    <apellidos> Diaz Santacruz </apellidos>
    <fecha_nacimiento>29/10/1977</fecha_nacimiento>
    <correos>
      <idcorreo>1</idcorreo>
      <correo>andres.diaz@unicauca.edu.co</correo>
    </correos>
    <correos>  
      <idcorreo>2</idcorreo>
      <correo>caandisa@hotmail.com</correo>
    </correos>
  </contacto>
  
  <contacto>
    <nombre>Isabel</nombre>
    <apellidos> Mejia</apellidos>
    <fecha_nacimiento>29/10/1977</fecha_nacimiento>
    <correos>
      <idcorreo>1</idcorreo>
      <correo>imejia@unicauca.edu.co</correo>
    </correos>
    <correos>
      <idcorreo>2</idcorreo>
      <correo>imejia@hotmail.com</correo>
    </correos>
  </contacto>

  <contacto>
    <nombre>Carlos Alberto</nombre>
    <apellidos>Cobos Lozada</apellidos>
    <fecha_nacimiento>11/02/1971</fecha_nacimiento>
    <correos>
      <idcorreo>1</idcorreo>
      <correo>ccobos@unicauca.edu.co</correo>
    </correos>
    <correos>
      <idcorreo>2</idcorreo>
      <correo>coboscarlos@gmail.com</correo>
    </correos>
  </contacto>
  
</listaContactos>
