=== manzamb/SemanticWebinAction/02 - XML - RDF/Solución XML/AppEjemploXML/Ejemplos 2/03-xml/ListaContactosMiguel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="listaContactos">
    <xs:complexType>
      <xs:sequence minOccurs="1" maxOccurs="unbounded">
        <xs:element ref="PERSONACONTACTO" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PERSONACONTACTO">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre" />
        <xs:element ref="apellidos" />
        <xs:element minOccurs="0" maxOccurs="1" ref="fechanacimiento" />
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="correos" />
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="telefonos" />
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="direcciones" />
        <xs:element minOccurs="0" maxOccurs="1" ref="relacion" />
      </xs:sequence>
      <xs:attribute default="profesional" name="tipoPersona">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="amigo" />
            <xs:enumeration value="familiar" />
            <xs:enumeration value="profesional" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="idpersona" type="xs:ID" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="correos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idcorreo" />
        <xs:element ref="descripcion" />
        <xs:element minOccurs="0" maxOccurs="1" ref="tipoc" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="telefonos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="idtelefono" />
        <xs:element ref="numero" />
      </xs:sequence>
      <xs:attribute name="tipoTelefono" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="oficina" />
            <xs:enumeration value="personal" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="indicativo" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="direcciones">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="iddireccion" />
        <xs:element ref="calle" />
        <xs:element ref="numerocasa" />
        <xs:element minOccurs="0" maxOccurs="1" ref="ciudad" />
        <xs:element minOccurs="0" maxOccurs="1" ref="pais" />
        <xs:element minOccurs="0" maxOccurs="1" ref="tipod" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="nombre" type="xs:string" />
  <xs:element name="apellidos" type="xs:string" />
  <xs:element name="fechanacimiento" type="xs:string" />
  <xs:element name="relacion">
    <xs:complexType>
      <xs:attribute name="amigo-de" type="xs:IDREFS" />
      <xs:attribute name="familiar-de" type="xs:IDREFS" />
    </xs:complexType>
  </xs:element>
  <xs:element name="idcorreo" type="xs:string" />
  <xs:element name="descripcion" type="xs:string" />
  <xs:element name="tipoc" type="xs:string" />
  <xs:element name="idtelefono" type="xs:string" />
  <xs:element name="numero" type="xs:string" />
  <xs:element name="iddireccion" type="xs:string" />
  <xs:element name="calle" type="xs:string" />
  <xs:element name="numerocasa" type="xs:string" />
  <xs:element name="ciudad" type="xs:string" />
  <xs:element name="pais" type="xs:string" />
  <xs:element name="tipod">
    <xs:complexType>
      <xs:attribute name="lugar">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="oficina" />
            <xs:enumeration value="casa" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== manzamb/SemanticWebinAction/02 - XML - RDF/Solución XML/AppEjemploXML/Ejemplos 2/03-xml/ListaContactosMiguel.xml
<?xml version="1.0" encoding="utf-8" ?>

<listaContactos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="./ListaContactosMiguel.xsd">
 
  <PERSONACONTACTO idpersona="ccobos" tipoPersona="amigo">
    <nombre>Carlos Alberto</nombre>
    <apellidos>Cobos Lozada</apellidos>
    <correos>
      <idcorreo>1</idcorreo>
      <descripcion>ccobos@unicauca.edu.co</descripcion>
    </correos>
    <correos>
      <idcorreo>2</idcorreo>
      <descripcion>cobos.carlos@hotmail.com</descripcion>
      <tipoc>personal</tipoc>
    </correos>
    <direcciones>
      <iddireccion>1</iddireccion>
      <calle>5</calle>
      <numerocasa>4-70</numerocasa>
      <ciudad>Popayán</ciudad>
      <pais>Colombia</pais>
      <tipod  lugar="oficina"/>
    </direcciones>
    <relacion amigo-de ="emezav" familiar-de="mmendoza"/>
  </PERSONACONTACTO>

  <PERSONACONTACTO idpersona="emezav" tipoPersona="profesional">
    <nombre>Erwin</nombre>
    <apellidos>Meza Vega</apellidos>
    <correos>
      <idcorreo>3</idcorreo>
      <descripcion>emezav@unicauca.edu.co</descripcion>
    </correos>
    <direcciones>
      <iddireccion>2</iddireccion>
      <calle>3</calle>
      <numerocasa>9-55</numerocasa>
      <ciudad>Bucaramanga</ciudad>
      <pais>Colombia</pais>
      <tipod  lugar="casa"/>
    </direcciones>
    <relacion amigo-de ="ccobos" familiar-de="mmendoza"/>
  </PERSONACONTACTO>

  <PERSONACONTACTO idpersona="mmendoza" tipoPersona="amigo">
    <nombre>Martha Eliana</nombre>
    <apellidos>Mendoza</apellidos>
    <correos>
      <idcorreo>4</idcorreo>
      <descripcion>mmendoza@unicauca.edu.co</descripcion>
    </correos>
    <direcciones>
      <iddireccion>3</iddireccion>
      <calle>5</calle>
      <numerocasa>4-70</numerocasa>
      <ciudad>Popayán</ciudad>
      <pais>Colombia</pais>
      <tipod  lugar="oficina"/>
    </direcciones>
    <relacion familiar-de="ccobos" amigo-de="emezav"/>
  </PERSONACONTACTO>

  <PERSONACONTACTO idpersona="samador" tipoPersona="amigo">
    <nombre>Siler</nombre>
    <apellidos>Amador Donado</apellidos>
    <fechanacimiento></fechanacimiento>
    <correos></correos>
  </PERSONACONTACTO>

  <PERSONACONTACTO idpersona="cardila" tipoPersona="amigo">
    <nombre>Carlos</nombre>
    <apellidos>Ardila</apellidos>
    <fechanacimiento></fechanacimiento>
    <correos></correos>
  </PERSONACONTACTO>
  
</listaContactos>
